module.exports = {
    contactUsHeaderText: 'Contact us',
    getinTouchText: 'GET IN TOUCH',
    reviewFormSuccessMessage: 'Success! Your details have been submitted successfully.',
    homePageTitle : 'Automation Exercise',
    subscriptionSuccessfulMessage : 'You have been successfully subscribed!',
    headerMenuProducts : 'Products',
    headerMenuCart : 'Cart',
    headerMenuSignUpLogin :'Signup / Login',
    headerMenuHome:'Home',
    allProductLabel : 'ALL PRODUCTS',
    searchedProductLabel : 'SEARCHED PRODUCTS',
    loginText : 'Login to your account',
    productAddedMessage : 'Your product has been added to cart.',
    shoppingCartText: 'Shopping Cart',
    emptyCartText : 'Cart is empty!',
    checkoutMessage : 'Register / Login account to proceed on checkout.',
    paymentHeading : 'Payment',
    orderPlacedText : 'ORDER PLACED!',
    orderConfirmedText : 'Congratulations! Your order has been confirmed!',
    signUpText : 'New User Signup!',
    accountCreatedText : 'ACCOUNT CREATED!',
    accountCreatedSuccessMessage : 'Congratulations! Your new account has been successfully created!',
    signUpErrorText : 'Email Address already exist!',
    successMessage : 'Thank you for your review.'
};